site_name: AeroGameFramework
site_description: Documentation for the AeroGameFramework
site_author: Stephen Leitnick
site_url: https://github.com/Sleitnick/AeroGameFramework

nav:
  - Home: index.md
  - Install & Setup: install.md
  - Services: services.md
  - Controllers: controllers.md
  - Modules: modules.md
  - Execution Model: execution_model.md
  - Module Docs:
      - Server:
        - Services:
          - StoreService: module_docs/server_services/store_service.md
        - Modules:
          - Data: module_docs/server_modules/data.md
      - Client:
        - Controllers:
          - UserInput: module_docs/client_controllers/user_input.md
          - Fade: module_docs/client_controllers/fade.md
          - TaskScheduler: module_docs/client_controllers/task_scheduler.md
        - Modules:
          - CameraShaker: module_docs/client_modules/camera_shaker.md
          - Smooth: module_docs/client_modules/smooth.md
          - Tween: module_docs/client_modules/tween.md
          - PID: module_docs/client_modules/pid.md
      - Shared Modules:
        - Base64: module_docs/shared/base64.md
        - Date: module_docs/shared/date.md
        - Event: module_docs/shared/event.md
        - ListenerList: module_docs/shared/listener_list.md
        - Promise: module_docs/shared/promise.md
        - StringUtil: module_docs/shared/string_util.md
        - TableUtil: module_docs/shared/table_util.md
        - Thread: module_docs/shared/thread.md

theme:
  logo: "img/logo_64.png"
  favicon: "img/logo_32.png"
  name: material
  palette:
    primary: blue
    accent: blue
  highlightjs: true
  hljs_languages:
    - lua

extra:
  social:
    - type: github
      link: https://github.com/Sleitnick/AeroGameFramework

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: true